### ISSUE TITLE
FieldProcessor Error Undefined Index: showDate

### ISSUE THREAD

**Issue by vimcat** [Pennebaker/craft-architect#16]
I have a super table that contains a couple of date fields:

![screen shot 2018-03-20 at 11 01 42 am](https://user-images.githubusercontent.com/76280/37674877-112d7744-2c31-11e8-8dbf-337f561313f6.png)

```
yii\base\ErrorException: Undefined index: showDate in .../vendor/pennebaker/craft-architect/src/base/FieldProcessor.php:392
Stack trace:
#0 .../vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(404): pennebaker\architect\base\FieldProcessor->export()
#1 .../vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(422): pennebaker\architect\base\FieldProcessor->export()
#2 .../vendor/pennebaker/craft-architect/src/controllers/DefaultController.php(128): pennebaker\architect\base\FieldProcessor->exportById()
#3 .../vendor/yiisoft/yii2/base/InlineAction.php(57): pennebaker\architect\controllers\DefaultController->actionExport()
#4 .../vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{.../vendor/yiisoft/yii2/base/InlineAction.php:57}()
#5 .../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#6 .../vendor/craftcms/cms/src/web/Controller.php(74): pennebaker\architect\controllers\DefaultController->runAction()
#7 .../vendor/yiisoft/yii2/base/Module.php(528): pennebaker\architect\controllers\DefaultController->runAction()
#8 .../vendor/craftcms/cms/src/web/Application.php(237): craft\web\Application->runAction()
#9 .../vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#10 .../vendor/craftcms/cms/src/web/Application.php(226): craft\web\Application->handleRequest()
#11 .../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#12 .../web/index.php(21): craft\web\Application->run()
#13 .../.composer/vendor/laravel/valet/server.php(133): ::unknown()
#14 {main}
```

The stack trace below happened because an entries field did not have the entry source defined (I fixed the field, but thought you might want to know anyway)

```
yii\base\ErrorException: Trying to get property of non-object in .../vendor/pennebaker/craft-architect/src/base/Processor.php:275
Stack trace:
#0 .../vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(276): pennebaker\architect\base\FieldProcessor->unmapSectionSources()
#1 .../vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(408): pennebaker\architect\base\FieldProcessor->unmapSources()
#2 .../vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(378): pennebaker\architect\base\FieldProcessor->export()
#3 .../vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(422): pennebaker\architect\base\FieldProcessor->export()
#4 .../vendor/pennebaker/craft-architect/src/controllers/DefaultController.php(128): pennebaker\architect\base\FieldProcessor->exportById()
#5 .../vendor/yiisoft/yii2/base/InlineAction.php(57): pennebaker\architect\controllers\DefaultController->actionExport()
#6 .../vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{.../vendor/yiisoft/yii2/base/InlineAction.php:57}()
#7 .../vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#8 .../vendor/craftcms/cms/src/web/Controller.php(74): pennebaker\architect\controllers\DefaultController->runAction()
#9 .../vendor/yiisoft/yii2/base/Module.php(528): pennebaker\architect\controllers\DefaultController->runAction()
#10 .../vendor/craftcms/cms/src/web/Application.php(237): craft\web\Application->runAction()
#11 .../vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#12 .../vendor/craftcms/cms/src/web/Application.php(226): craft\web\Application->handleRequest()
#13 .../vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#14 .../web/index.php(21): craft\web\Application->run()
#15 .../.composer/vendor/laravel/valet/server.php(133): ::unknown()
#16 {main}
```

**Comment by spAnser** [comment]
Is this something that you imported? or is it something that you attempted to export.

**Comment by vimcat** [comment]
This was something I tried to export
