### ISSUE TITLE
I'm getting an internal server error for most export options.

### ISSUE THREAD

**Issue by Kashkin** [Pennebaker/craft-architect#40]
```TypeError: Argument 1 passed to craft\services\Sites::getSiteById() must be of the type integer, string given, called in /path/to/app/vendor/pennebaker/craft-architect/src/base/Processor.php on line 297 and defined in /path/to/app/vendor/craftcms/cms/src/services/Sites.php:605
Stack trace:
#0 /path/to/app/vendor/pennebaker/craft-architect/src/base/Processor.php(297): craft\services\Sites->getSiteById('*')
#1 /path/to/app/vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(594): pennebaker\architect\base\Processor->unmapSites('*')
#2 /path/to/app/vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(751): pennebaker\architect\base\FieldProcessor->unmapSources(Array)
#3 /path/to/app/vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(737): pennebaker\architect\base\FieldProcessor->export(Object(typedlinkfield\fields\LinkField), Array, true)
#4 /path/to/app/vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(672): pennebaker\architect\base\FieldProcessor->export(Object(verbb\supertable\fields\SuperTableField), Array, true)
#5 /path/to/app/vendor/pennebaker/craft-architect/src/base/FieldProcessor.php(765): pennebaker\architect\base\FieldProcessor->export(Object(craft\fields\Matrix))
#6 /path/to/app/vendor/pennebaker/craft-architect/src/controllers/DefaultController.php(140): pennebaker\architect\base\FieldProcessor->exportById('9')
#7 [internal function]: pennebaker\architect\controllers\DefaultController->actionExport()
#8 /path/to/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /path/to/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /path/to/app/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('export', Array)
#11 /path/to/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('export', Array)
#12 /path/to/app/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('architect/defau...', Array)
#13 /path/to/app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('architect/defau...', Array)
#14 /path/to/app/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#15 /path/to/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /path/to/app/public/index.php(24): yii\base\Application->run()
#17 {main}

**Comment by spAnser** [comment]
What version of craft are you on?

Also do you have more of the trace output?

**Comment by Kashkin** [comment]
Sorry, I've updated the output.

Also, I'm using:
PHP version | 7.1.30
Craft Pro | 3.2.5.1
Architect | 2.3.1

**Comment by spAnser** [comment]
Thanks will update when I find some info. Is that a LinkField in side a SuperTable that is inside a Matrix :)

**Comment by Kashkin** [comment]
Yes, it would be. How's that for an edge case!
