### ISSUE TITLE
Calling unknown method: craft\web\twig\variables\CraftVariable::userGroups()

### ISSUE THREAD

**Issue by noandrea** [Pennebaker/craft-architect#5]
Error using architect with the latest craftcms RC

k | v
-- | --
PHP version | 7.1.9
Database driver & version | MySQL 5.7.21
Image driver & version | GD 7.1.9
Craft edition & version | Craft Personal 3.0.0-RC10.1
Yii version | 2.0.13.1
Twig version | 2.4.4
Guzzle version | 6.2.1
Imagine version | 0.7-dev

stacktrace
```
Twig_Error_Runtime: Calling unknown method: craft\web\twig\variables\CraftVariable::userGroups() in /data/craft/vendor/pennebaker/craft-architect/src/templates/_blueprints/user_groups.twig:15
Stack trace:
#0 /data/craft/storage/runtime/compiled_templates/cc/ccda443aaa9bc84536e661e8a5a68bc2f51348cb3fb4816dbb0d12b4bc7f0ba8.php(43): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\web\twig\variables\CraftVariable), 'userGroups', Array)
#1 /data/craft/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_fd32e014d2a8120216cecf926f98f5dc4a3327c0987dd6c8408dce6ece4759a1->doDisplay(Array, Array)
#2 /data/craft/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /data/craft/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#4 /data/craft/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#5 /data/craft/storage/runtime/compiled_templates/e2/e2302a014906f1789b6fbb665879304ecf356ac779be288bb878606f3b8d1957.php(86): craft\web\twig\Template->display(Array)
#6 /data/craft/vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_e5ca011c90f3796a859469710b6b400ca7f14ec83c22e962d5ec947d356a13a1->doDisplay(Array, Array)
#7 /data/craft/vendor/craftcms/cms/src/web/twig/Template.php(51): Twig_Template->displayWithErrorHandling(Array, Array)
#8 /data/craft/vendor/twig/twig/lib/Twig/Template.php(366): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#9 /data/craft/vendor/craftcms/cms/src/web/twig/Template.php(32): Twig_Template->display(Array, Array)
#10 /data/craft/vendor/twig/twig/lib/Twig/Template.php(374): craft\web\twig\Template->display(Array)
#11 /data/craft/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#12 /data/craft/vendor/craftcms/cms/src/web/View.php(308): Twig_Environment->render('architect/expor...', Array)
#13 /data/craft/vendor/craftcms/cms/src/web/View.php(356): craft\web\View->renderTemplate('architect/expor...', Array)
#14 /data/craft/vendor/craftcms/cms/src/web/Controller.php(120): craft\web\View->renderPageTemplate('architect/expor...', Array)
#15 /data/craft/vendor/pennebaker/craft-architect/src/controllers/CpController.php(62): craft\web\Controller->renderTemplate('architect/expor...')
#16 [internal function]: pennebaker\architect\controllers\CpController->actionExport()
#17 /data/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /data/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#19 /data/craft/vendor/craftcms/cms/src/web/Controller.php(80): yii\base\Controller->runAction('export', Array)
#20 /data/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('export', Array)
#21 /data/craft/vendor/craftcms/cms/src/web/Application.php(240): yii\base\Module->runAction('architect/cp/ex...', Array)
#22 /data/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('architect/cp/ex...', Array)
#23 /data/craft/vendor/craftcms/cms/src/web/Application.php(216): yii\web\Application->handleRequest(Object(craft\web\Request))
#24 /data/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#25 /data/craft/web/index.php(21): yii\base\Application->run()
#26 {main}
```

**Comment by spAnser** [comment]
I am also on the latest beta in my dev environment. What were you doing at the time of the error?

**Comment by spAnser** [comment]
Ah I am on the pro trial to test user group stuff I forget craft wont let you do those with personal craft let me downgrade and make sure it detects the craft license level to prevent calling functions that won't work on it

**Comment by noandrea** [comment]
yep, when upgrading to pro license the exception goes away.
thanks!
